services:
  zoomsdk: &zoomsdk
    build: ./
    platform: linux/amd64
    volumes:
     - .:/tmp/meeting-sdk-linux-sample
    ports:
      - "3000:3000"
    command: ["--join-url", "https://us04web.zoom.us/j/79301442827?pwd=B1dMhLavwgInaCkOIclOogFgWbimMb"]

